format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $mise\
  $golang\
  $nodejs\
  $python\
  $ruby\
  $rust\
  $kubernetes\
  $memory_usage\
  $env_var\
  $cmd_duration\
  $custom\
  $battery\

  $line_break\

  $jobs\
  $time\
  $character\
"""

[character]
success_symbol = "[❯](bold yellow)"
error_symbol = "[❯](bold bright-red)"

[hostname]
style = "bright-cyan"

[directory]
style = "blue"

[git_status]
style = "bright-yellow"
# disabled = true
format = '([$all_status$ahead_behind]($style) )'
deleted = "×"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = ""
untracked = "∅"
stashed = ""
modified ="○"
renamed = ""
staged = "●"

[git_branch]
symbol = " "
style = "bright-green"

[kubernetes]
style = "cyan"
symbol = "↗ "
disabled = false

[ruby]
symbol = " "

[nodejs]
symbol = "⬢ "

[mise]
disabled = false
symbol = ""
format = '[$symbol$health]($style) '
style = "purple"
